### PR TITLE
Mommi illegals

### PR DESCRIPTION
**Pull request by Asd396**
Illegals module can now be used on MoMMIs. It removes their muteness and killswitch along with allowing their laws to be changed. If a MoMMI's laws are changed from keeper it disables keeper safeguards and if a MoMMI is given keeper it'll enable them. Added a keeper board to AI upload. Unrestricted MoMMIs have green eyes. Addresses issue #14

### CODE REVIEW

**Comment by octareenroon91** [comment]
Can you confirm that emag_act aborts/fails for mommi with the illegals module?  That's a key feature of the illegals module.

**Comment by Asd396** [comment]
Illegals fails on emagged MoMMIs but not vice versa, since they're not quite equivalent. Should this be changed? If so, adding a check in emag_act for scrambledcodes should suffice.

**Comment by octareenroon91** [comment]
Yes, please.  The standard effect of the illegals module blocks out future emag attempts.

Note the R.SetEmagged(1) on https://github.com/Zaers/-tg-station/blob/master/code/game/objects/items/robot/robot_upgrades.dm#L193

Adding a check right after this line might work well:
https://github.com/Zaers/-tg-station/blob/master/code/modules/mob/living/silicon/mommi/mommi.dm#L361

emag_act() has actually needed a failure-if-already-emagged notice for a while, actually.  I'll look at this tomorrow and probably just pull and apply patches at this point.

Thank you.

**Comment by Asd396** [comment]
Done

**Pull request merged**
