### PR TITLE
Organs rewrite

### PR DESCRIPTION
**Pull request by Asd396**
Ported over Ricotez' unfinished organ system rewrite. Basically each carbon has an organsystem containing organ datums, which contain the actual organ items, which contain information like damage and DNA. This allows dismemberment and checking each limb and drawing the sprite based on that. Ready for live testing now!

Dismemberment works now! To test, use a weapon that can dismember (eswords, fire axes and chainsaws currently), amputation surgery, or the admin organ manipulation verb.

Known issues:
* Because of the way sprites work humans always show hands when viewed from the sides. Also when one of your arms or legs is removed your gloves disappear from sight (it was either this or not seeing that the limb is removed)
* Humans don't have icons when examined

Todo:
* Sprites
  * Missing species (human_parts.dmi and human_parts_greyscale.dmi)
  * Bloody stumps

Extra stuff:
* Balance dismemberment rates
* Shadowling stuff controlled by the organsystem
* Mutations controlled by organs
* Draw 'X' on unusable inventory slots
* Move sight procs to eyes and fix alium darksight eyes on humans
* Actual limbs with locational damage for all carbons (except slimes. Why are they carbons again?)
* Add sutures so some of the surgeries make more sense
* Broken limbs
* Tongue or vocal chords as an organ. Their DNA would determine your voice, and they could be manipulated with a scalpel to produce a different one.
* More internal organs, like liver and kidneys (missing them makes you take toxin damage constantly), stomach (can't keep anything down). Other internal organs might have diseases linked to them (like appendicitis right now) so medbay might want to keep an organ bank for people who have a kidney failure or who require heart transplants
* Chainsaw arms, peg legs and other silliness

### CODE REVIEW

**Comment by Asd396** [comment]
Does anyone know at which point a human has his DNA complete?

**Comment by Koriath** [comment]
Should look in the gib proc, or ex_act to make limbs fly around in random directions when someone is gibbed. No brain should survive (to prevent cloning, which is the main use of gibbing someone) but the rest should be scattered.

**Comment by octareenroon91** [comment]
Some gibbing does leave the brain behind.  It's an option when calling the proc.

**Comment by Asd396** [comment]
Alright, as far as I'm concerned we're good for live testing

**Comment by Asd396** [comment]
As far as I'm concerned we're good for live testing. Might want to disable all mutantraces from roundstart or just the ones that don't have sprites yet.

**Comment by Asd396** [comment]
>he merged it into master

ABSOLUTE
MADMAN
I hope you're ready to deal with esoteric as fuck bugs. And we still don't have all the species sprites, do we?

**Pull request merged**
