### PR TITLE
Le Unstable Man of Repeating Digits

### PR DESCRIPTION
**Pull request by The-Albinobigfoot**
Adds a translucent raincoat the the traitor uplink and a bundle to feature it.
Also adds 'Winter Coats' to the top of clothing/suits/miscellaneous.dm, for autism's sake.

All credit goes to Arthurdentist of /vg/
Relevant PRs:
https://github.com/d3athrow/vgstation13/pull/2879
https://github.com/d3athrow/vgstation13/pull/2891

### CODE REVIEW

**Comment by Koriath** [comment]
Neato. But now you'll get half the player base screaming at you for a way to implement "doubles".

**Comment by The-Albinobigfoot** [comment]
You know, it might have been possible if we didn't do away with NTSL. Probably for the better that we can't, though.

**Comment by octareenroon91** [comment]
I have made a miscalculation: the axe doesn't have a sprite when worn in the exosuit slot.  That may or may make the suit axe a bigger balance issue than I was thinking.

**Comment by The-Albinobigfoot** [comment]
Yeah, I noticed that. Let's encourage people to examine each other more often. The perfect solution.

**Pull request merged**
