### PR TITLE
Bad dragon

### PR DESCRIPTION
**Pull request by Koriath**
Alright, spawner fixed, and can be safely spawned by admins too.
3 sizes.

### CODE REVIEW

**Comment by octareenroon91** [comment]
OK, this needs a few touch-ups: config/admin changes

**Comment by Koriath** [comment]
Sure, but for what?
Damage/availability?

**Comment by octareenroon91** [comment]
You've got changes on old config data and regression of my snacks tablecraft and vomit patches.

Pulling updates as merges is a recipe for trouble, and not necessary.

**Comment by Koriath** [comment]
Uh. I usually pull the latest Zaers code and merge into my master before making new branches.
Not sure what happened this time then. I'll make a newer clean branch I guess.

**Pull request closed without merging**
